/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosVirtualScrollRouteImport } from './routes/demos/virtual-scroll'
import { Route as DemosResumableUploadRouteImport } from './routes/demos/resumable-upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosVirtualScrollRoute = DemosVirtualScrollRouteImport.update({
  id: '/demos/virtual-scroll',
  path: '/demos/virtual-scroll',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosResumableUploadRoute = DemosResumableUploadRouteImport.update({
  id: '/demos/resumable-upload',
  path: '/demos/resumable-upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demos/resumable-upload': typeof DemosResumableUploadRoute
  '/demos/virtual-scroll': typeof DemosVirtualScrollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demos/resumable-upload': typeof DemosResumableUploadRoute
  '/demos/virtual-scroll': typeof DemosVirtualScrollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demos/resumable-upload': typeof DemosResumableUploadRoute
  '/demos/virtual-scroll': typeof DemosVirtualScrollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demos/resumable-upload' | '/demos/virtual-scroll'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demos/resumable-upload' | '/demos/virtual-scroll'
  id: '__root__' | '/' | '/demos/resumable-upload' | '/demos/virtual-scroll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemosResumableUploadRoute: typeof DemosResumableUploadRoute
  DemosVirtualScrollRoute: typeof DemosVirtualScrollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/virtual-scroll': {
      id: '/demos/virtual-scroll'
      path: '/demos/virtual-scroll'
      fullPath: '/demos/virtual-scroll'
      preLoaderRoute: typeof DemosVirtualScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/resumable-upload': {
      id: '/demos/resumable-upload'
      path: '/demos/resumable-upload'
      fullPath: '/demos/resumable-upload'
      preLoaderRoute: typeof DemosResumableUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemosResumableUploadRoute: DemosResumableUploadRoute,
  DemosVirtualScrollRoute: DemosVirtualScrollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
